# Generated by Django 3.2.3 on 2021-05-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='collect',
            old_name='lname',
            new_name='lastname',
        ),
    ]
