# Generated by Django 3.2.3 on 2021-05-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210517_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='BloodPressure',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='collect',
            name='BloodSugar',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='collect',
            name='Pulse',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='collect',
            name='SpO2',
            field=models.CharField(default='', max_length=3),
        ),
    ]
