# Generated by Django 3.2.3 on 2021-05-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210518_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='BloodPressure',
        ),
        migrations.AddField(
            model_name='collect',
            name='BloodPressureDiastolic',
            field=models.CharField(default='Default', max_length=4),
        ),
        migrations.AddField(
            model_name='collect',
            name='BloodPressureSystolic',
            field=models.CharField(default='Default', max_length=4),
        ),
        migrations.AlterField(
            model_name='collect',
            name='BloodSugar',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='collect',
            name='Pulse',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='collect',
            name='SpO2',
            field=models.CharField(max_length=3),
        ),
    ]
