# Generated by Django 3.2.3 on 2021-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20210518_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='Cough',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collect',
            name='Fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collect',
            name='Headache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collect',
            name='InaCrowdedPlace',
            field=models.BooleanField(default=False),
        ),
    ]
