# Generated by Django 3.2.3 on 2021-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20210518_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='Email',
            field=models.EmailField(default='Default@gmail.com', max_length=254),
        ),
    ]
