# Generated by Django 3.2.3 on 2021-05-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_collect_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='Key',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
