# Generated by Django 3.2.3 on 2021-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='Key',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='lastname',
        ),
        migrations.AddField(
            model_name='collect',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='collect',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
